### ISSUE TITLE
Feature: Open VSX Registry

### ISSUE THREAD

**Issue by matbgn** [azat-io/eyecons#1]
### Describe the feature

Hi,

Is there any plan to add it also to the Open VSX Registry https://open-vsx.org/ ?

e.g. to install it on VSCodium

Best,

### Validations

- [X] Check that there isn't [already an issue](https://github.com/azat-io/eyecons/issues) that reports the same feature to avoid creating a duplicate.

**Comment by azat-io** [comment]
Hi, Thank you for your issue. I will read the Open VSX Registry documentation and make a release today.

**Comment by azat-io** [comment]
Added in e7f3e7c1af0c0d3f9867e30e58f70a41ef98fcb8.
