### ISSUE TITLE
Theme Request: (One Monokai)

### ISSUE THREAD

**Issue by waldymarxthf** [azat-io/eyecons#2]
### Describe the theme

The One Monokai theme is very similar to the Monokai Pro theme. Has a large number of downloads and stars, I would like to see it

https://github.com/azemoh/vscode-one-monokai

### Additional comments

По братски, очень нужно

### Validations

- [X] Check that there isn't [already an issue](https://github.com/azat-io/eyecons/issues) that reports the same feature to avoid creating a duplicate.

**Comment by azat-io** [comment]
Added in 9a3f73e. Released in [v1.3.0](https://github.com/azat-io/eyecons/releases/tag/v1.3.0).
