### ISSUE TITLE
Feature: Add Compatibility with Cursor Editor

### ISSUE THREAD

**Issue by m1rn** [azat-io/eyecons#3]
### Describe the feature

Hi,

First of all, thank you for the fantastic work on the Eyecons extension! It significantly enhances the visual experience in coding, and I find it very useful.

However, I’ve recently started using **Cursor**, an editor built on VSCode, and I noticed that the Eyecons extension is currently not compatible with it. Since both Cursor and VSCode share a lot of similarities, it would be incredibly helpful if Eyecons could be made compatible with the Cursor editor as well.

Would it be possible to add support for Cursor in a future update? I believe many users of both tools would greatly benefit from this enhancement.

Thank you for your time and consideration!

### Validations

- [X] Check that there isn't [already an issue](https://github.com/azat-io/eyecons/issues) that reports the same feature to avoid creating a duplicate.

**Comment by azat-io** [comment]
Fixed in f049f805879e3c19a7b238a02c614e8a958e2f0f.
